# 语法要求:
# 1. k: v  （ k v 之间是空格区分, : 不能少 ）
# 2. 属性有层级关系,使用下一行,空两个空格(空格几个都行)
# 3. 只要左侧对其,代表同一层级属性

#  ● 大小写敏感
#  ● 使用缩进表示层级关系，k: v，使用空格分割k,v
#  ● 缩进时不允许使用Tab键，只允许使用空格。换行
#  ● 缩进的空格数目不重要，只要相同层级的元素左侧对齐即可
#  ● # 表示注释，从这个字符一直到行尾，都会被解析器忽略。

#  ● birthDay 推荐写为 birth-day
#  ● 文本：
#  ○ 单引号不会转义【\n 则为普通字符串显示】
#  ○ 双引号会转义【\n会显示为换行符】
#  ● 大文本
#  ○ |开头，大文本写在下层，保留文本格式，换行符正确显示
#  ○ >开头，大文本写在下层，折叠换行符
#  ● 多文档合并
#  ○ 使用---可以把多个yaml文档合并在一个文档中，每个文档区依然认为内容独立

server:
  port: 9999

spring:
  servlet:
    multipart:
      max-file-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379

person:
  name: 张三
  age: 18
  birthDay: 2010/10/10 12:12:12
  like: true
  child:
    name: 李四
    age: 20
    birthDay: 2018/10/10
    text: [ "abc","def" ]
  dogs:
    - name: 小黑
      age: 3
    - name: 小白
      age: 2
  cats:
    c1:
      name: 小蓝
      age: 3
    c2: { name: 小绿,age: 2 } #对象也可用{}表示